---
- hosts: webservers
  become: true
  tasks:
    - name: install java
      yum:
        name:  java
        state: latest
    - name: download tomcat package
      get_url:
        url: http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.51/bin/apache-tomcat-8.5.51.tar.gz
        dest: /usr/local
    - name: archieving
      unarchive:
        src: /usr/local/apache-tomcat-8.5.51.tar.gz
        dest: /usr/local
        remote_src: yes
    - name: start the service
      shell: nohup /usr/local/apache-tomcat-8.5.51/bin/startup.sh &
  
    - name: Check that war file exist
      stat:
        path: /usr/local/apache-tomcat-8.5.51/webapps/gameoflife.war
      register: stat_result
 
    - name: Delete the war file, if it exist already
      file:
        path: /usr/local/apache-tomcat-8.5.51/webapps/gameoflife.war
        state: absent
      when: stat_result.stat.exists == True
    - name: Check that GAMEOFLIFE dir exist
      stat:
        path: /usr/local/apache-tomcat-8.5.51/webapps/gameoflife
      register: stat_result
    - name: Delete the GAMEOFLIFE dir, if it exist already
      file:
        path: /usr/local/apache-tomcat-8.5.51/webapps/gameoflife
        state: absent
      when: stat_result.stat.exists == True
    - name: Deploy War File
      get_url:
        url: http://13.232.104.88:8081/nexus/service/local/artifact/maven/redirect?r=releases&g=oracle&a=game&p=war&v=LATEST
        dest: /usr/local/apache-tomcat-8.5.51/webapps/gameoflife.war
